name: Quality check

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  arduino-check:
    uses: sensirion/.github/.github/workflows/shared.arduino.check.yml@main
    with:
      lint-lib-manager-check: submit
      fqbn-list: "['arduino:avr:mega','esp32:esp32:esp32']"
      dependency-list: "auto"

  code-generation-check:
    uses: sensirion/.github/.github/workflows/driver.generated.metadata_check.yml@main
