name: Quality check

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  arduino-quality:
    uses: sensirion/.github/.github/workflows/driver.arduino.check.yml@main
    with:
      expect-arduino-examples: true
      lint-lib-manager-check: submit
      fqbn-list: "['arduino:avr:mega','esp32:esp32:esp32']"
      dependency-list: "auto"  
